#!/usr/bin/env bash
# Sanity-check the repo before kicking off a release build.
#
# Verifies:
#   - project.yml is parseable by xcodegen.
#   - MARKETING_VERSION matches the most recent RELEASE_NOTES.md heading.
#   - LICENSE and SECURITY.md exist.
#   - .gitignore contains the expected ignore globs.
set -euo pipefail

cd "$(dirname "$0")/.."

fail=0

if ! command -v xcodegen >/dev/null 2>&1; then
  echo "error: xcodegen not installed"
  fail=1
fi

if ! xcodegen --spec project.yml --use-cache 2>&1 | grep -q "Created project" ; then
  echo "warn: xcodegen did not regenerate the project — assuming up to date"
fi

VERSION="$(grep 'MARKETING_VERSION:' project.yml | head -1 | awk '{print $2}' | tr -d '"')"
if [[ -z "$VERSION" ]]; then
  echo "error: could not parse MARKETING_VERSION from project.yml"
  fail=1
fi

if ! grep -q "^## ${VERSION}" RELEASE_NOTES.md && ! grep -q "^## ${VERSION} " RELEASE_NOTES.md ; then
  echo "warn: RELEASE_NOTES.md has no heading for ${VERSION} — releases without notes are confusing"
fi

for f in LICENSE SECURITY.md README.md ARCHITECTURE.md; do
  if [[ ! -f "$f" ]]; then
    echo "error: $f is missing"
    fail=1
  fi
done

if ! grep -q '\.xcodeproj/' .gitignore ; then
  echo "error: .gitignore must ignore *.xcodeproj/ (generated by xcodegen)"
  fail=1
fi

if [[ $fail -eq 0 ]]; then
  echo "release identity audit ok (version $VERSION)"
fi
exit $fail
